import localFont from "next/font/local";
import "../globals.css";

import initTranslations from "../../i18n";

import HeightProvider from "@/components/HeightProvider";
import NavBar from "@/components/NavBar";
import SearchBar from "@/components/SearchBar";
import ThemeProvider from "@/components/ThemeProvider";
import ToastNotification from "@/components/ToastNotification";
import TranslationsProvider from "@/components/TranslationsProvider";
import StoreProvider from "../store/storeProvider";

const arpona = localFont({
  src: [
    {
      path: "../fonts/ArponaLight.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/ArponaRegular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/ArponaMedium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/ArponaSemoBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/ArponaBold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-arpona",
});
const helveticaNeue = localFont({
  src: [
    {
      path: "../fonts/helvetica_Neue/HelveticaNeueUltraLight.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../fonts/helvetica_Neue/HelveticaNeueThin.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../fonts/helvetica_Neue/HelveticaNeueLight.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/helvetica_Neue/HelveticaNeueRoman.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/helvetica_Neue/HelveticaNeueMedium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/helvetica_Neue/HelveticaNeueBold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/helvetica_Neue/HelveticaNeueHeavy.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/helvetica_Neue/HelveticaNeueBlack.otf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-helveticaNeue",
});
const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: any) {
  // console.log(params.locale);
  const param = await params;
  const locale = param.locale;
  const { t, resources } = await initTranslations(locale, ["Home"]);
  // const urlParams = useParams();
  console.log(`Params : ${locale}`);
  console.log(`Params : ${param}`);
  console.log(param);
  console.log(`Params : ${param.theme}`);

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={` ${helveticaNeue.variable} ${geistSans.variable} ${geistMono.variable} antialiased scrollbar-hide`}
      >
        <StoreProvider>
          <HeightProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
              forcedTheme={undefined}
            >
              <ToastNotification />
              <div className="flex flex-col gap-10 pt-10">
                <TranslationsProvider locale={locale} namespaces={["Home"]} resources={resources}>
                  <SearchBar />
                  <NavBar />
                  {children}
                </TranslationsProvider>
              </div>
            </ThemeProvider>
          </HeightProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
